<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en" ng-app="myApp" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en" ng-app="myApp" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en" ng-app="myApp" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" ng-app="wizard" class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Gator Trax - Boat Builder Wizard</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--    <link rel="stylesheet" href="skin/frontend/rwd/default/js/bower_components/html5-boilerplate/css/normalize.css">-->
<!--    <link rel="stylesheet" href="skin/frontend/rwd/default/js/bower_components/html5-boilerplate/css/main.css">-->
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<!--    <link rel="stylesheet" href="css/app.css"/>-->
    <link href='http://fonts.googleapis.com/css?family=Bevan|Open+Sans:400italic,700italic,400,300,700' rel='stylesheet' type='text/css'>
</head>
<body ng-cloak class="ng-cloak">

<!--    <ul class="nav">
        <li ui-sref-active="active"><a class="brand" ui-sref="home">Home</a></li>
        <li ui-sref-active="active"><a class="brand" ui-sref="boatModel">Model</a></li>
    </ul>-->


<div ng-controller="ScoreboardCtrl">
    <button type="button" id="getStuff" onclick="getStuff()">Get Stuff</button>
    <script type="text/javascript">
        function getStuff()
        {
            jQuery.get("boatbuilder/ajax/save", function(data){
                console.log(data);
            });
        }
    </script>
</div>

<div ui-view></div>

<div ng-controller="BuilderCtrl">
    <accordion>
        <accordion-group heading="{{section.title}}" ng-repeat="section in sections" ng-click="LoadSection(section)" is-open="section.open">
            <div ui-view="{{section.route}}"></div>
        </accordion-group>
    </accordion>
</div>
<div ng-controller="ButtonCtrl">
    <button ng-click="saveForLater(section)">
        Save for Later
    </button>
    <button ng-click="submitForQuote(section)">
        Submit for Quote
    </button>
</div>

<!--<script src="js/config.js"></script>-->

<!--<script src="../bower_components/angular/angular.js"></script>-->
<!--<script src="../bower_components/angular-route/angular-route.min.js"></script>-->
<!--<script src="../bower_components/angular-animate/angular-animate.min.js"></script>-->
<!--<script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.12.0.js"></script>-->
<!--<script src="../bower_components/angular-ui-router/release/angular-ui-router.min.js"></script>-->
<!--<script src="../bower_components/html5-boilerplate/js/vendor/modernizr-2.6.2.min.js"></script>-->
<!--<script src="../bower_components/pouchdb/dist/pouchdb.min.js"></script>-->

<!--<script src="app.js"></script>-->
<!--<script src="js/controllers.js"></script>-->
<!--<script src="modules/scoreboard/scoreboard.js"></script>-->
<!--<script src="modules/deck/deck.js"></script>-->
<!--<script src="modules/look/look.js"></script>-->
<!--<script src="modules/electrical/electrical.js"></script>-->
<!--<script src="modules/flooring/flooring.js"></script>-->
<!--<script src="modules/fuelTank/fuelTank.js"></script>-->
<!--<script src="modules/accessories/accessories.js"></script>-->
<!--<script src="modules/trailer/trailer.js"></script>-->
<!--<script src="modules/seatsRacksBrackets/seatsRacksBrackets.js"></script>-->
<!--<script src="modules/boatModel/boatModel.js"></script>-->
<!--<script src="modules/hullSize/hullSize.js"></script>-->
<!--<script src="modules/motor/motor.js"></script>-->
<!--<script src="modules/interior/interior.js"></script>-->
<!--<script src="modules/saveForLater/saveForLater.js"></script>-->
</body>
</html>
